name: flask-redis
services:
  app:
    image: flask
    pull_policy: build
    build: ./app
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 5000:5000
    networks:
      - app-net

  redis:
    image: redis:6-alpine
    healthcheck:
      test: ["CMD-SHELL","redis-cli --raw incr ping"]
      interval: 1m
      timeout: 30s
      retries: 3
    restart: always
    networks:
      - app-net


networks:
  app-net:
